[package]
name = "speakmcp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
enigo = "0.3.0"

[profile.release]
strip = true
